# backend-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: matching-backend
  template:
    metadata:
      labels:
        app: matching-backend
    spec:
      containers:
      - name: matching-backend
        image: 0628-9434-2784.dkr.ecr.us-east-1.amazonaws.com/matching-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "job-matching-database.cwpofmfg5t4m.us-east-1.rds.amazonaws.com"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password

