version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies..."
      - rm -rf node_modules  # Clean the node_modules directory
      - npm install
  pre_build:
    commands:
      - echo "Starting pre_build phase..."
      - printenv | grep DOCKERHUB_USERNAME
      - printenv | grep DOCKERHUB_ACCESS_TOKEN

