version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Basic install phase"
      - rm -rf node_modules  # Clean the node_modules directory
      - npm install

