version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies..."
      - rm -rf node_modules  # Clean the node_modules directory
      - npm install
  pre_build:
    commands:
      - echo "DOCKERHUB_USERNAME: $DOCKERHUB_USERNAME"

