version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_ACCESS_TOKEN | docker login --username $DOCKERHUB_USERNAME --password-stdin
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t matching-backend .
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 0628-9434-2784.dkr.ecr.us-east-1.amazonaws.com)
      - docker tag matching-backend:latest 0628-9434-2784.dkr.ecr.us-east-1.amazonaws.com/matching-backend:latest
      - docker push 0628-9434-2784.dkr.ecr.us-east-1.amazonaws.com/matching-backend:latest

