version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USERNAME: docker-token:username
    DOCKERHUB_ACCESS_TOKEN: docker-token:password

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies..."
      - rm -rf node_modules  # Clean the node_modules directory
      - npm install
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo $DOCKERHUB_ACCESS_TOKEN | docker login --username $DOCKERHUB_USERNAME --password-stdin
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t matching-frontend .
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 062894342784.dkr.ecr.us-east-1.amazonaws.com
      - docker tag matching-frontend:latest 062894342784.dkr.ecr.us-east-1.amazonaws.com/matching-frontend:latest
      - docker push 062894342784.dkr.ecr.us-east-1.amazonaws.com/matching-frontend:latest
artifacts:
  files:
    - '**/*'

