version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin 0628-9434-2784.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t matching-backend .
      - docker tag matching-backend:latest 0628-9434-2784.dkr.ecr.us-east-1.amazonaws.com/matching-backend:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 0628-9434-2784.dkr.ecr.us-east-1.amazonaws.com/matching-backend:latest

env:
  secrets-manager:
    DOCKER_USERNAME: "docker-token:username"
    DOCKER_PASSWORD: "docker-token:password"

