version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USERNAME: docker-token:username
    DOCKERHUB_ACCESS_TOKEN: docker-token:password
  variables:
    GIT_URL: "https://github.com/memoor72/job-matching-platform.git"

phases:
  install:
    runtime-versions:
      docker: 19
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_ACCESS_TOKEN | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 062894342784.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t matching-backend .
      - docker tag matching-backend:latest 062894342784.dkr.ecr.us-east-1.amazonaws.com/matching-backend:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 062894342784.dkr.ecr.us-east-1.amazonaws.com/matching-backend:latest
artifacts:
  files:
    - '**/*'
