# frontend-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-frontend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: matching-frontend
  template:
    metadata:
      labels:
        app: matching-frontend
    spec:
      serviceAccountName: ecr-access
      containers:
      - name: matching-frontend
        image: 062894342784.dkr.ecr.us-east-1.amazonaws.com/matching-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

